before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
builds:
  - binary: innctl
    main: ./
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X cmd.Version={{.Version}}

release:
  prerelease: auto

universal_binaries:
  - replace: true

checksum:
  name_template: "checksums.txt"
